on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
      working-directory: ./backend
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      working-directory: ./backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ICLOUD_DEVICE_ID: ${{ secrets.ICLOUD_DEVICE_ID }}
        ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        ICLOUD_USERNAME: ${{ secrets.ICLOUD_USERNAME }}
        SECRETS: ${{ secrets.SECRETS }}